PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?position1 ?position2 ?equal

WHERE{ 

  VALUES ( ?position1 ?position2) {

    ( "1 m"^^cdt:ucum "1 m"^^cdt:ucum )
    ( "1 m"^^cdt:length "1.0e6 um"^^cdt:length )

    ( "1 m"^^cdt:ucum "1 m"^^cdt:length )
    ( "1 m"^^cdt:length "1 m"^^cdt:ucum )

    ( "1 [ft_br]"^^cdt:length "0.30479976 m"^^cdt:length )

    # stored as double -> 15 to 17 significant digits
    ( "1.01204507800120450 m"^^cdt:ucum "1.01204507800120459 m"^^cdt:ucum )

    ( "3.6 km/h"^^cdt:ucum "1 m/s"^^cdt:ucum )
  }

  BIND( ?position1 = ?position2 AS ?equal )
  
}
