PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 s-1"^^cdt:radioactivity # per second 
    "1 Bq"^^cdt:radioactivity # becquerel
    "1 Ci"^^cdt:radioactivity # Curie 

  }

  # normalize 
  BIND("0 Bq"^^cdt:radioactivity + ?value AS ?normalized )
  
}