PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 WB/M2"^^cdt:magneticFluxDensity # weber per square meter
    "1 T"^^cdt:magneticFluxDensity # tesla
    "1 GS"^^cdt:magneticFluxDensity # gauss

  }

  # normalize 
  BIND("0 T"^^cdt:magneticFluxDensity + ?value AS ?normalized )
  
}