PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 J/s"^^cdt:power # joule per second
    "1 W"^^cdt:power # watt
    "1 [ft_i].[lbf_av]/s"^^cdt:power # definition of horse power
    "1 [HP]"^^cdt:power # horsepower

  }

  # normalize 
  BIND("0 W"^^cdt:power + ?value AS ?normalized )
  
}