PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 C/s"^^cdt:electricCurrent # coulomb per second
    "1 A"^^cdt:electricCurrent # ampère 
    "1 mA"^^cdt:electricCurrent # milliampère 
    "1 Bi"^^cdt:electricCurrent # Biot 

  }

  # normalize 
  BIND("0 A"^^cdt:electricCurrent + ?value AS ?normalized )
  
}