PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 km"^^cdt:length
    "1.609344E+6 mm"^^cdt:length
    "5280 [ft_i]"^^cdt:length

  }

  # normalize 
  BIND("0 m"^^cdt:length + ?value AS ?normalized )
  
}