PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

      "1 m/s2 "^^cdt:acceleration # S.I.
      "3.8 [g]"^^cdt:acceleration # standard acceleration of free fall
      "1.57e-2 cm/s2"^^cdt:acceleration # S.I. equiv. of Gal
      "1.57e-2 Gal"^^cdt:acceleration # Gal


  }

  # normalize 
  BIND("0 m/s2"^^cdt:acceleration + ?value AS ?normalized )
  
}