PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 MOL/S"^^cdt:catalyticActivity # mole per second
    "1 KAT"^^cdt:catalyticActivity # KATAL
    "1 U"^^cdt:catalyticActivity # Unit

  }

  # normalize
  BIND("0 MOL/S"^^cdt:catalyticActivity + ?value AS ?normalized )
  
}