PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 Pa"^^cdt:pressure # pascal
    "1 bar"^^cdt:pressure # bar
    "1 atm"^^cdt:pressure # standard atmosphere 
    "1 att"^^cdt:pressure # technical atmosphere

  }

  # normalize 
  BIND("0 Pa"^^cdt:pressure + ?value AS ?normalized )
  
}