PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?position ?normalized 

WHERE{ 

  VALUES ?position {

  	# valid length 

		"1 um"^^cdt:length
		"1 um"^^cdt:ucum 

		"1 m"^^cdt:length
		"1.0 m"^^cdt:length
		"-1.0 m"^^cdt:length
		"1.0e-3 m"^^cdt:length 

		"1 km"^^cdt:length 
		"1 km"^^cdt:ucum

		"1 Mm"^^cdt:length 
		"1 Gm"^^cdt:length 
    	"1 [ft_i]"^^cdt:length 
		"1 [nmi_i]"^^cdt:length 
		"1 [hd_i]"^^cdt:length 
		"1 [ft_br]"^^cdt:length 

		"1 [ft_br].h/s"^^cdt:length 

		# not valid length

		"abc m"^^cdt:length
		"1m"^^cdt:length 
		"abc1 km"^^cdt:length  
		"1 m/s"^^cdt:length }

  # convert to meters
  BIND("0 m"^^cdt:ucum + ?position AS ?normalized )
  
}
# order in ascending order
ORDER BY ?position