PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value1 ?value2 ?result

WHERE{ 

  VALUES ( ?value1 ?value2 ) {

    # multiply measures
    
    ( "1.0 m"^^cdt:length "2 m"^^cdt:length ) 
    ( "1.0 m/s"^^cdt:speed "2 s"^^cdt:time )
    ( "1.0 m/s"^^cdt:ucum "2 s"^^cdt:ucum )

    # multiply measure by scalar
    
    ( "1.0 m/s"^^cdt:ucum "2"^^xsd:int )
    ( "1.0 m/s"^^cdt:ucum "2"^^xsd:double )
    ( "1.0 m/s"^^cdt:ucum "2"^^xsd:decimal )
    ( "1.0 m/s"^^cdt:speed "2"^^xsd:float )

    # multiply scalar by measure
    
    ( "2"^^xsd:int "1.0 m/s"^^cdt:ucum )
    ( "2"^^xsd:double "1.0 m/s"^^cdt:ucum )
    ( "2"^^xsd:decimal "1.0 m/s"^^cdt:ucum )
    ( "2"^^xsd:float "1.0 m/s"^^cdt:speed )

  }

  BIND( ?value1 * ?value2 AS ?result )
  
}
