PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 m2"^^cdt:area # square meter
    "1 ar"^^cdt:area # are
    "1 [sin_i]"^^cdt:area # square inch International customary units
    "1 [in_i]2"^^cdt:area # square inch International customary units
    "1 [smi_us]"^^cdt:area # square mile Older U.S. “survey” lengths (also called "statute" lengths)

  }

  # normalize
  BIND("0 m2"^^cdt:area + ?value AS ?normalized )
  
}