PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 KG.M/S2"^^cdt:force # S.I. equiv. of Newton
    "1 N"^^cdt:force # Newton
    "1 GF"^^cdt:force # gram-force
    "1 G.[G]"^^cdt:force # gram-force
    "1 DYN"^^cdt:force # dyne
    "1 g.cm/s2"^^cdt:force # S.I. equiv. of dyne

  }

  # normalize 
  BIND("0 KG.M/S2"^^cdt:force + ?value AS ?normalized )
  
}