PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 /Ohm"^^cdt:electricConductance # inverse of Ohm 
    "1 Ohm-1"^^cdt:electricConductance # inverse of Ohm 
    "1 S"^^cdt:electricConductance # siemens 

  }

  # normalize 
  BIND("0 /Ohm"^^cdt:electricConductance + ?value AS ?normalized )
  
}