PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

      "1.2 mol"^^cdt:amountOfSubstance

  }

  # normalize 
  BIND("0 mol"^^cdt:acceleration + ?value AS ?normalized )
  
}