PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "120 m/s"^^cdt:speed # meter per second 
    "90 km/h"^^cdt:speed # kilometer per hour
    "90 km.h-1"^^cdt:speed # kilometer per hour

  }

  # normalize 
  BIND("0 m/s"^^cdt:speed + ?value AS ?normalized )
  
}