PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 kg.m2/s2"^^cdt:energy # S.I. unit for energy
    "1 N.m"^^cdt:energy # Newton meter
    "1 W.s"^^cdt:energy # Watt second
    "1 kW.h"^^cdt:energy # kiloWatt hour
    "1 erg "^^cdt:energy # erg 
    "1 eV"^^cdt:energy # electronvolt 
    "1 J"^^cdt:energy # joule
    "1 cal"^^cdt:energy # calorie
    "1 [Cal]"^^cdt:energy # nutrition label Calories

  }

  # normalize 
  BIND("0 kg.m2/s2"^^cdt:energy + ?value AS ?normalized )
  
}