PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 KG.M2/S2"^^cdt:energy # S.I. unit for energy
    "1 N.M"^^cdt:energy # Newton meter
    "1 W.S"^^cdt:energy # Watt second
    "1 KW.HR"^^cdt:energy # kiloWatt hour
    "1 ERG "^^cdt:energy # erg 
    "1 EV"^^cdt:energy # electronvolt 
    "1 J"^^cdt:energy # joule
    "1 CAL"^^cdt:energy # calorie
    "1 [CAL]"^^cdt:energy # nutrition label Calories

  }

  # normalize 
  BIND("0 kg.m2/s2"^^cdt:energy + ?value AS ?normalized )
  
}