PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value1 ?value2 ?sum

WHERE{ 

  VALUES ( ?value1 ?value2 ) {

    ( "1 m"^^cdt:length "2 um"^^cdt:length )

    ( "1 m"^^cdt:ucum "1 m"^^cdt:ucum )
    ( "1 m"^^cdt:ucum "1 s"^^cdt:ucum )
    ( "1 m"^^cdt:length "1 s"^^cdt:length )
    ( "1 m"^^cdt:length "1 s"^^cdt:time )

    # stored as double -> 15 to 17 significant digits
    ( "1.0123456789123456789 m"^^cdt:ucum "0.0 m"^^cdt:length )

    ( "3.6 km/h"^^cdt:ucum "-1 m/s"^^cdt:ucum )
  }

  BIND( ?value1 + ?value2 AS ?sum )
  
}
