PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "273.15 K"^^cdt:temperature # kelvin 
    "37.5 CEL"^^cdt:temperature # degree Celsius
    "100 [DEGF]"^^cdt:temperature # degree Fahrenheit
    "100 [DEGR]"^^cdt:temperature # degree Rankine
    "100 [DEGRE]"^^cdt:temperature # degree Réaumur 

  }

  # normalize 
  BIND("0 CEL"^^cdt:temperature + ?value AS ?normalized )
  
}