PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?position1 ?position2 ?equal

WHERE{ 

  VALUES ( ?position1 ?position2) {

    ( "1 M"^^cdt:ucum "1 M"^^cdt:ucum )
    ( "1 M"^^cdt:length "1.0e6 UM"^^cdt:length )

    ( "1 M"^^cdt:ucum "1 M"^^cdt:length )
    ( "1 M"^^cdt:length "1 M"^^cdt:ucum )

    ( "1 [FT_BR]"^^cdt:length "0.30479976 M"^^cdt:length )

    # stored as double -> 15 to 17 significant digits
    ( "1.01204507800120450 M"^^cdt:ucum "1.01204507800120459 M"^^cdt:ucum )

    ( "3.6 KM/HR"^^cdt:ucum "1 M/S"^^cdt:ucum )
  }

  BIND( ?position1 = ?position2 AS ?equal )
  
}
