PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 "^^cdt:dimensionless # Unit (empty string)
    "1 [PI]"^^cdt:dimensionless # PI
    "1 %"^^cdt:dimensionless # mole per second
    "1 [PPTH]"^^cdt:dimensionless # perts per thousand
    "1 [PPM]"^^cdt:dimensionless # perts per million
    "1 [PPB]"^^cdt:dimensionless # perts per billion
    "1 [PPTR]"^^cdt:dimensionless # perts per trillion

  }

  # normalize 
  BIND("0 "^^cdt:dimensionless + ?value AS ?normalized )
  
}