PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 "^^cdt:dimensionless # Unit (empty string)
    "1 [pi]"^^cdt:dimensionless # pi
    "1 %"^^cdt:dimensionless # percent
    "1 [ppth]"^^cdt:dimensionless # parts per thousand
    "1 [ppm]"^^cdt:dimensionless # parts per million
    "1 [ppb]"^^cdt:dimensionless # parts per billion
    "1 [pptr]"^^cdt:dimensionless # parts per trillion

  }

  # normalize 
  BIND("0 "^^cdt:dimensionless + ?value AS ?normalized )
  
}