PREFIX iter: <http://w3id.org/sparql-generate/iter/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt: <http://w3id.org/lindt/custom_datatypes#> 
PREFIX ex: <http://example.org/>

SELECT ?value ?normalized 

WHERE{ 

  VALUES ?value {

    "1 g"^^cdt:mass # gram
    "1 kg"^^cdt:mass # kilogram
    "1 t"^^cdt:mass # tonne
    "1 u"^^cdt:mass # unified atomic mass unit 
    "1 [m_e]"^^cdt:mass # electron mass 
    "1 [gr]"^^cdt:mass # grain (avoirdupois weight system)
    "1 [oz_av]"^^cdt:mass # ounce (avoirdupois weight system)

  }

  # normalize 
  BIND("0 kg"^^cdt:mass + ?value AS ?normalized )
  
}